"use client";

import { type NextPage } from "next";
import Head from "next/head";
import Calendar from "../components/calendar/Calendar";

import { api } from "~/utils/api";
import { useState } from "react";
import { type DateType } from "~/utils/types";
import Menu from "~/components/Menu";
import Spinner from "~/components/Spinner";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const [date, setDate] = useState<DateType>({
    justDate: null,
    dateTime: null,
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {!date.dateTime && <Calendar date={date} setDate={setDate} />}
        {date.dateTime && false ? (
          <Menu />
        ) : (
          <div className="flex h-screen items-center justify-center">
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
